services:
    web:
        build: .
        ports:
            - "5000:5050"
        volumes:
            - .:/app
        env_file:
            - ./.env
    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data:
            